### ISSUE TITLE
Clean-up (& some suggestions)

### ISSUE THREAD

**Issue by mundschenk-at** [dylandownhill/WP-Content-Security-Policy-Plugin#3]
@dylandownhill, there are some things I need to know before I start the clean-up:
* Are you comfortable with Grunt and Composer? For my plugins I now use Composer for the development dependencies (PHPUnit, PHPCS etc.) and Grunt for the general workflow (deployment to WP.org SVN, CSS minification etc.).
* Is it OK if I restructure the directories a bit? Currently, the project is very deeply nested and, probably for deployment reasons, mimics the SVN structure. This is not necessary with a Grunt workflow. One level of indirection is OK, but I personally prefer to be able to run plugins directly from the repository directory. (It's your decision, my only strong opinion is that `trunk` needs to go.)
* The WordPress Coding Standards mandate `snake_case` for variable names, including class properties. Is it OK for me to change everything to that format?

Some suggestions not directly related to the clean-up:
* Use autoloading (either a custom autoloader or via Composer.
* Check the necessary pre-requisites on activation (e.g. PHP version) and fail gracefully otherwise. An example can be seen in [`mundschenk-at/wp-typography`](https://github.com/mundschenk-at/wp-typography/blob/master/wp-typography.php#L57). I've already extracted the necessary classes to a Composer library, so reusing the code would be easy.
* Don't run code during inclusion of a PHP file if at all possible (some static initialization would be OK, but no WordPress functions). There should be a kind of plugin controller separate from the `WP_REST_Controller` to do the general plugin initialization an set up the hooks.
* Use SASS for writing CSS.

**Comment by dylandownhill** [comment]
Go ahead and make the changes. I was keeping Git and SVN in sync, it doesn't matter in reality, I can just cut and paste into the trunk on the SVN branch.

**Comment by mundschenk-at** [comment]
Great! I will add a PR when I've got something to show.

**Comment by S1SYPHOS** [comment]
Additionally, unless already planned, I'd suggest splitting classes & files for better maintainability & general overview. I'm planning a CSP plugin for [Kirby CMS](https://getkirby.com) and will definitely look into the progress you are making, maybe even contribute at some point.

Thanks for this great plugin and keep up the good work!

**Comment by mundschenk-at** [comment]
@dylandownhill Have you had a chance to look at the preliminary PR (#4)?

@S1SYPHOS Yes, although I'd see that as a second step after the initial clean-up.

**Comment by mundschenk-at** [comment]
@dylandownhill ping

**Comment by dylandownhill** [comment]
Sorry, work has been really busy lately. Haven't had a chance to look just yet.

**Comment by mundschenk-at** [comment]
Oh you merged that already? I was just after some feedback about the direction pf the proposed changes (wanted to tick off the other two points as well before finalizing the PR).
